version: '3.8'

services:
  theia-ide:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - UID=1000
        - GID=1000
    ports:
      - "3000:3000"
    volumes:
      # Mount workspace to persist work
      - ./workspace:/theia/workspace:rw
      # Optional: mount additional plugins
      - ./plugins:/theia/plugins:rw
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: theia-ide

